"""
Auto-generated Pydantic models from template-config.schema.json
Do not edit this file manually - it will be overwritten
"""

from typing import Any, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict

Fieldtype = Literal[
    "string", "integer", "number", "boolean", "array", "object"
]  # Basic data types for configuration fields


class Fieldvalidation(BaseModel):
    required: Optional[bool] = None  # Whether the field is required
    minLength: Optional[int] = None  # Minimum string length
    maxLength: Optional[int] = None  # Maximum string length
    pattern: Optional[str] = None  # Regular expression pattern for validation
    min: Optional[Union[int, float]] = None  # Minimum numeric value
    max: Optional[Union[int, float]] = None  # Maximum numeric value
    minItems: Optional[int] = None  # Minimum number of items in array
    maxItems: Optional[int] = None  # Maximum number of items in array
    enum: Optional[list[str]] = None  # List of allowed values

    model_config = ConfigDict(extra="forbid")


class Configfield(BaseModel):
    key: str  # Unique identifier for the configuration field
    type: Fieldtype
    description: Optional[str] = None  # Human-readable description of the field
    default: Optional[Any] = None  # Default value for the field
    validation: Optional[Fieldvalidation] = None

    model_config = ConfigDict(extra="forbid")


class Runtimerequirements(BaseModel):
    memory: str  # Memory requirement (e.g., '4GB', '512MB')
    cpu: str  # CPU requirement (e.g., '2 cores', '1 core')
    gpu: bool  # Whether GPU is required
    estimatedLatency: Optional[str] = None  # Estimated response latency (e.g., '500ms')

    model_config = ConfigDict(extra="forbid")


class TemplateConfigSchema(BaseModel):
    """Simplified schema for agent template configurations"""

    name: str  # Human-readable name of the template
    description: Optional[str] = None  # Description of the template
    version: str  # Semantic version of the template
    config: list[Configfield]  # Configuration fields as an ordered array

    model_config = ConfigDict(extra="forbid")
